### ISSUE TITLE
fix: Modal behavior on iOS

### ISSUE THREAD

**Issue by Johnnycus** [nexxtway/react-rainbow#1031]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

Modal component doesn't have a scroll bar on iOS (both Safari and Chrome). Scrollbar is visible and is working in Google Dev Tools but not on the actual iOS device.

## To Reproduce 🕹

1. Create a Modal component
2. Add a lot of text or elements inside to make it scrollable
3. Check the Modal on iOS device
4. See that it's not scrollable

## Expected Behavior 🤔

It should allow scrolling when inside text or elements are taking a lot of space

## Current Behavior 😯

No scrolling on iOS devices which makes it impossible to read the text

## Your Environment 🌎

**Smartphone (please complete the following information):**

-   Device: iPhone X
-   OS: iOS 12
-   Browser Chrome, Safari

**Comment by reiniergs** [comment]
probably adding `-webkit-overflow-scrolling: touch;` to the Modal content container It will solve that issue

**Comment by Johnnycus** [comment]
> probably adding `-webkit-overflow-scrolling: touch;` to the Modal content container It will solve that issue

That doesn't help, unfortunately. I have spent some time today trying to fix this issue but wasn't able to.

**Comment by reiniergs** [comment]
it's not going to work because this component is preventing scroll in the body `body lock approach`, check this https://github.com/nexxtway/react-rainbow/blob/master/src/components/Modal/index.js#L38 

@LeandroTorresSicilia this needs to be a more elegant solution. check this out https://github.com/willmcpo/body-scroll-lock 

/cc @TahimiLeonBravo

**Comment by TahimiLeonBravo** [comment]
@Johnnycus We have already fixed the modal issue in IOS. This is now available in the new release v1.6.0

**Comment by Johnnycus** [comment]
> @Johnnycus We have already fixed the modal issue in IOS. This is now available in the new release v1.6.0

Thanks for the Modal fix but after updating to a new version my app doesn't work because there is no "styled" folder in node_modules/react-rainbow-components. See the [issue](https://github.com/nexxtway/react-rainbow/issues/1050)
