### ISSUE TITLE
fix: Version 1.6.0 – can't find styles which prevents app start

### ISSUE THREAD

**Issue by Johnnycus** [nexxtway/react-rainbow#1050]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

If you update React Rainbow Components to v1.6.0 you won't be able to run the app. It throws errors like:
`Module not found: Can't resolve '../../../../styles/borderRadius' in '.../node_modules/react-rainbow-components/components/Input/inputCheckbox/styled'`

## To Reproduce 🕹

1. Install or update React Rainbow Components to v1.6.0
2. Add any component to the app
3. Run or build the app

**Desktop (please complete the following information):**

-   OS: macOS Mojave

**Comment by LeandroTorresSicilia** [comment]
@Johnnycus fixed in version 1.6.1
