### ISSUE TITLE
feat: DatePicker, DateTimePicker and Calendar Localize texts

### ISSUE THREAD

**Issue by FouMez** [nexxtway/react-rainbow#1075]
Hi,
is there a possibility to customize texts of months and days or change them to another language?

**Comment by LeandroTorresSicilia** [comment]
Right now that is not possible but this needs to be done.
For that we need to:
1- pass a locale to Application component, then there is a context where all components can access to the locale.
2- pass a locale prop to Calendar and DatePicker components so the consumer can use them without use the Application.
3- The locale prop passed directly to components have precedence over the context one (passed to Application).

**Comment by TahimiLeonBravo** [comment]
Hi @FouMez 
There is a new version 1.9.0 where we add the localization to the `Calendar`, `DatePicker` and `DateTimePicker`
This prop was added in the pr #1117

**Comment by FouMez** [comment]
Thank you so much for being reactive. 
Keep going !
