### ISSUE TITLE
feat: Modal close button

### ISSUE THREAD

**Issue by FouMez** [nexxtway/react-rainbow#1108]
Hello ! 
Can you please add the possibility to hide the close button of a modal, i'm doing it manually by overriding the CSS class but it's not very effective to do so. 

Thank you for this great project !

**Comment by TahimiLeonBravo** [comment]
Hi @FouMez 
Thanks for the suggestion,
Please, we would like to know a little more about the use case you have to understand why you need to hide the close button on the Modal.

**Comment by FouMez** [comment]
Hi @TahimiLeonBravo 
sometimes i use modals to block the access to some content of my apps , for example if the user have an unverified email or have some payment issues, i will block all app features with a modal that cannot be closed.

**Comment by TahimiLeonBravo** [comment]
Hi @FouMez
There is a new version 1.8.0 where we add a new prop `hideCloseButton` to hide the close button of a modal.
This prop was added in the pr #1115.
Thank for the feedback.

**Comment by FouMez** [comment]
Thank you so much for being reactive. 
Keep going !
