### ISSUE TITLE
feat: Table features

### ISSUE THREAD

**Issue by FouMez** [nexxtway/react-rainbow#1130]
Hello !
i have some features suggestions for Table and Column  components:
1) add a prop to control the height of the column. 
2) tables are not very responsive, the data gets truncated when the window width is not sufficient.
3) the scroll on x-axis on a column only appears when i try to resize the column, it would be easier if there's a prop that controls the appearance of the scroll or if it appears automatically based on the
content length.
4) when adding the prop component to a Column, the component will receive the props "row" and "value" if you add the index to the prop row it will facilitate the manipulation specially when trying to remove that row
Thank you !

**Comment by LeandroTorresSicilia** [comment]
Hi @FouMez, thanks for the suggestions, some thoughts on each point:
1. What do you mean by the height of the column? Can you elaborate more on this point?
2. I agree with you, we definitively need to improve this.
3. @TahimiLeonBravo Follow the suggestion for more details.
4. I agree 100% with you, what we can do is send another argument with the index, it also should be added to the MenuItem onClick event when using a Column of type "action".

**Comment by TahimiLeonBravo** [comment]
> 3. the scroll on x-axis on a column only appears when i try to resize the column, it would be easier if there's a prop that controls the appearance of the scroll or if it appears automatically based on the
>    content length.

Hi @FouMez
I'm 100% onboard with you.
I think that horizontal scrolling is inevitable when presenting large datasets and when this happens we present a UX-UI problem in the Table. 
To produce a pleasurable experience in the Table we have to provide some clues:
1. We have to add "affordance" to the solution, allows the user to determinate that the scrolling action is possible to do. 
2. We have to add a "signifier", a signal that says to the user where and how he can do scrolling.

**Comment by FouMez** [comment]
Hi @LeandroTorresSicilia i'm so sorry for taking too long to respond i was on vacation,
So about the height of the column, i meant the height of the row sorry.
For example if i have a custom component to display on a column (like buttons for example). the height of the row is always fixed to 5em and there's no way to change it unless i override the concerned CSS class which is not really a good practice because it will affect other tables on my app, 

Thank you team ! you're the best.

**Comment by LeandroTorresSicilia** [comment]
Great @FouMez 
You are right, making CSS introspection is not good and we need to add a way to change the height of rows.
Thanks for the feedback.

**Comment by TahimiLeonBravo** [comment]
@FouMez 
We are launching a new release of react-rainbow-components v1.13.0 🎉
Some of these features have been added. We are going to close this issue :) 
if you have more suggestions lets create new issues
