### ISSUE TITLE
fix: keyboard navigation in Picklist component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1152]
#### View the video:
https://drive.google.com/drive/u/1/folders/1rZEIq4TxqbFkdyaCu8g-Sh7Zym1dHaBJ

#### Platform and Operating System:
- macOS Catalina v10.15.2 Beta
     - GoogleChrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by ykabusalah** [comment]
Would I be able to tackle this issue as well?

**Comment by TahimiLeonBravo** [comment]
> Would I be able to tackle this issue as well?

Hi @ykabusalah you are welcome to collaborate :)
We could not reproduce this bug again
Can you reproduce this?
