### ISSUE TITLE
fix: styles when the days of the `Calendar` component get `focus`

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1154]
Tabbing through the Calendar component there is no visual change when the selected day gets focus due to current styles.

### Requirements
- Fix the styles when a day is focus
- Fix the styles when the selected-day is focus
- Add styles when the selected-day is hover

#### Create a new variable for the shadow:
`$shadow-outline-3: 0 0 4px $color-brand;`

#### Link Design
https://zpl.io/a7vLJZK

**Comment by ykabusalah** [comment]
can i get this?

**Comment by ykabusalah** [comment]
Would I be able to tackle this issue?

**Comment by TahimiLeonBravo** [comment]
> Would I be able to tackle this issue?

Hi @ykabusalah you are welcome to collaborate :)

**Comment by ykabusalah** [comment]
Awesome thank you! Can I get assigned on this?

**Comment by TahimiLeonBravo** [comment]
> Awesome thank you! Can I get assigned on this?

Sure!

**Comment by HellWolf93** [comment]
I can't access to the design link. Please invite me to the projects.
