### ISSUE TITLE
fix: add arrows to the Lookup when displaying many options

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1155]
### Requirements
- [ ] Show arrow up/down functionality when are many options to show in the dropdown menu
- [ ] Add unit test for this functionality
- [ ] Add integration test

### Spec
- It should render an arrow down/up when are many options to show
- It should scrolling when the user hovers over the arrows

Please follow to the Picklist behavior for more details
https://react-rainbow.web.app/#!/Picklist/3

### Unit Test Spec
- [ ] should render scroll down arrow when the number of children is more than five
- [ ] should not render scroll down arrow when the number of children is less than five
- [ ] should not render scroll up arrow when menu scroll position is zero
- [ ] should render scroll up arrow when popup menu scroll position is greater than zero

### Design
https://zpl.io/aw4Algj

**Comment by TahimiLeonBravo** [comment]
@rafaelmg83

**Comment by rafaelmg83** [comment]
Ok, perfect, i started to work on it already.
