### ISSUE TITLE
test: add integration-test to `reorder-child` functionality in all components

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1157]
- [x] Accordion (https://zpl.io/VYR5ELd)
- [ ] CarouselCard (https://zpl.io/bJvwYAD)
- [ ] PrimitiveMenu (https://zpl.io/adkNDyL)
- [ ] Tabset (https://zpl.io/VODL45r)
- [ ] Add test-case for when unregister child in `Tabset`, `Accordion`, `CarouselCard`, `PrimitiveMenu` and `Picklist` components

**Comment by yvmunayev** [comment]
@TahimiLeonBravo I check the Picklist component tests and start
