### ISSUE TITLE
fix: input styles when getting focus clicking in the label

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1165]
#### Description
When in the input is passed the error prop and the user clicking in the label, the border styles color flashing displaying a color blue.

Please view the video attached for a better understanding
https://drive.google.com/file/d/1nUdAu7_YwG5bWzM71fQrs46glzatqrPG/view?usp=sharing

#### Actual Result
The border styles in the Input flashing when it gets the focus clicking in the label element.

#### Expected Result
The behavior when the input gets the focus clicking in the label should be the same that when it gets the focus clicking in the input element.

**Comment by TahimiLeonBravo** [comment]
Hi @yvmunayev, you can go inside this issue

**Comment by yvmunayev** [comment]
Hi @TahimiLeonBravo
