### ISSUE TITLE
fix: unexpected focus styles of the Table in Safari

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1167]
### Description
When the header of the table is clicked unexpected focus styles are rendered on the cell clicked and on the cell of the column.

#### Steps to reproduce:
1. Go to the Table example
2. Select one cell on the header of the Table
3. Hover over the cells of the column

Please view the video attached for a better understanding
https://drive.google.com/file/d/1Nu-wXVU2_hA8ZSYvZ2bibjN6n9-Dh46Q/view?usp=sharing

### Platform and Operating System:
- MacOS Catalina version 10.15.2 Beta 
      - Safari Version 13.0.4

**Comment by ernesto-tapia** [comment]
Hi, I would like to work on this issue

**Comment by reiniergs** [comment]
go for it!

**Comment by ernesto-tapia** [comment]
Hello, 
After some testing in safari, we found that the unexpected blue outline can be suppressed by adding `outline:none` in the table header .focus component, this achieves that the page styles are the same to the other browsers. Is there a problem if we use this approach to solve the issue? or is it necessary to have the outline available for other parts of the code?

**Comment by LeandroTorresSicilia** [comment]
I think this could be the right solution, submit a PR and then we will check it
