### ISSUE TITLE
question: How to style components?

### ISSUE THREAD

**Issue by egeucak** [nexxtway/react-rainbow#1181]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

**Is your feature request related to a problem? Please describe.**
I can't change text color to white in Tab component

## Expected Behavior 🤔
Being able to change the color and background the way I like

## Context 🔦
I want to change the color of text in Tab's that is defined by `label` field, but I couldn't figure out how.

**Describe the solution you'd like**
A working style property might be great

**Describe alternatives you've considered**
A text color prop might work as well.

**Comment by LeandroTorresSicilia** [comment]
@egeucak We are working on add theming support, there is an issue open # 1172 for this. Right now the only way to do this is using className prop and making introspection (which is bad practice) like:
```
.my-tab button {
    color: '#fff';
}
```
The recommended approach to make customization is with a theme. We will release a new version as soon as possible with the theme support.

**Comment by TahimiLeonBravo** [comment]
Hi @egeucak 
We are launching a new release of react-rainbow-components v1.13.0 🎉
This feature has been added, we are going to close this issue :)
