### ISSUE TITLE
feat: add support Theme for CheckboxToggle  component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1190]
https://github.com/nexxtway/react-rainbow/projects/1#card-29896923

**Comment by yvmunayev** [comment]
@TahimiLeonBravo assign this task

**Comment by yvmunayev** [comment]
@TahimiLeonBravo @LeandroTorresSicilia for this component you need to define the COLOR_BRAND_2, I think it is best to make a function that calculates them
