### ISSUE TITLE
test: add test `hour24` to the TimePicker component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1234]
# Unit test Specs

## get24HourTime
- [x] should return the right 24 hour when 'ampm' has incorrect value

## getInputValue
- [x] should return "--:--" when hour24 is true and value and placeholder are falsy

## getNextHour
- [x] should return the string "0" when no value is passed and hour24 is true
- [x] should return the string "0" when value passed converted to Number is equal to 23 and hour24 is true
- [x] should return the string of the value passed increased by 1 when value passed converted to Number is different to 23 and hour24 is true

## getPrevHour
- [x] should return the string "23" when no value is passed and hour24 is true
- [x] should return the string "23" when value passed converted to Number is equal to 0 and hour24 is true
- [x] should return the string of the value passed decreased by 1 when value passed converted to Number is different to 0 and hour24 is true

## normalizeHour
- [x] should return "00" when the value passed is "000" and hour24 is true
- [ ] should return the value passed when the value is between 12 and 20 and hour24 is true

## timePicker
- [x] should initialize value state to the right value when hour24 is passed
- [x] should initialize value state to the right value when hour24 is not passed
- [x] should set the right value state when value prop is changed dynamically

## timeSelect
- [x] should set the right value when hour24 is true and hour value changes
- [x] should not change focus when hour24 is true and minute value changes
- [x] should not change focus when hour24 is true, minute input has focus and right key is pressed
- [x] should call onChange when press enter key while hour, minutes have value and hour24 is passed
- [x] should not render ampm input when hour24 is true

# Integration test Specs
- [ ] Add specs here

**Comment by HellWolf93** [comment]
@LeandroTorresSicilia check the specs

**Comment by LeandroTorresSicilia** [comment]
@HellWolf93 
We should add tests case to all files changed in this PR
https://github.com/nexxtway/react-rainbow/pull/1230/files
since here is where this feature was added
for example, in this PR the ```src/components/TimePicker/helpers/getInputValue.js``` file was changed and the line:
```if (hour24) return value || '--:--';```
was added to it
then we need to test this new case where '--:--' is returned when hour24 is passed in the ```src/components/TimePicker/helpers/__test__/getInputValue.spec.js``` test file
and then the same for all files changed in this pr

**Comment by HellWolf93** [comment]
@LeandroTorresSicilia ok i think i got it. Can you check it again?
