### ISSUE TITLE
feat: add `hour24` prop to the DateTimePicker component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1235]

**Comment by skayred** [comment]
Hello, do you have any estimates on that fix?

**Comment by TahimiLeonBravo** [comment]
Hi, @skayred we are focused on the theme feature but we will add priority to this feature, I think that in the next weeks the feature will be released.
You are welcome to collaborate to react-rainbow :)

**Comment by skayred** [comment]
@TahimiLeonBravo thanks a lot for the information!

**Comment by skayred** [comment]
Hello, are there any plans for publishing this update as an NPM package? NPM version doesn't have this fix

**Comment by TahimiLeonBravo** [comment]
Hi @skayred 
We are launching a new release of react-rainbow-components v1.13.0 🎉
This feature already is available on this version :)
