### ISSUE TITLE
test: add test to AvatarGroup component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1253]
#### helpers: abbreviateNumber
- [ ] should return a formatted number using SI

#### AvatarGroup
- [ ] should pass the props to children as expected

#### Avatars
- [ ] should render default amount (3) of Avatar components when none maxAvatars is passed
- [ ] should render right amount of Avatar components when maxAvatars is passed
- [ ] should Avatar components have the right props passed
- [ ] should render an img when src or icon prop is passed
- [ ] should render an abbr when initials prop is passed

#### Counter
- [ ] should have the right size passed
- [ ] should render the total amount number of avatars passed

**Comment by LeandroTorresSicilia** [comment]
#### helpers: abbreviateNumber
- [ ] should return the same number passed when it is less than 1000 (add here an array with some cases like [8, 75, 999])
- [ ] should attach `k` suffix when number is greater than 1000 and less than ... (same ^^ add some cases with differents digits each one)
- [ ] should attach `M` suffix ...
- [ ] should attach `G` suffix ...
also here add a test case for wrong values 

#### AvatarGroup
- [ ] should pass the prop showCounter as isTrue to RenderIf component

#### Avatars
- [ ] should render default amount (3) of Avatar components when none maxAvatars is passed
- [ ] should render right amount of Avatar components when maxAvatars is passed
- [ ] should pass the right zIndex to each Avatar

#### Counter
- [ ] should have the right size passed
- [ ] should render the total amount number of avatars passed

#### Counter
- [ ] should call abbreviateNumber with the total of avatars
- [ ] should render the total amount number of avatars passed (note that here you need to check  that the text rendered is what return the mock of abbreviateNumber)
