### ISSUE TITLE
Css Styles Not Exist

### ISSUE THREAD

**Issue by ebrahimhassan121** [nexxtway/react-rainbow#1307]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

No Style Exist for all classes
##Screenshots
![Screen Shot 2020-02-06 at 2 40 12 PM](https://user-images.githubusercontent.com/22202170/73938563-31054000-48f0-11ea-844b-2426b7dd989d.png)

## To Reproduce 🕹

1. normal installation

## Expected Behavior 🤔
![Screen Shot 2020-02-06 at 2 53 33 PM](https://user-images.githubusercontent.com/22202170/73938824-bbe63a80-48f0-11ea-8475-3ed33b205325.png)

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: Mac Os
-   Browser : Chrome & safari

**Comment by TahimiLeonBravo** [comment]
Hi, @ebrahimhassan121 are you wrapping your application with the `<Application />` component?
If you are trying to use the global classNames you need to wrap your application with the `<Application />` component. The `<Application />` component is the one who imports the global styles.

**Comment by ebrahimhassan121** [comment]
yes , i already wrapping it

**Comment by TahimiLeonBravo** [comment]
> yes , i already wrapping it

Hello @ebrahimhassan121 !
I'm going to need a little more context to solve the issue.
What is the version of `react-rainbow-component` you are using?
Is this issue happening when you use all classes or does it happen with a specific one?
