### ISSUE TITLE
feat: add flexible table column height

### ISSUE THREAD

**Issue by ighotouch** [nexxtway/react-rainbow#1359]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

**Is your feature request related to a problem? Please describe.**

## Expected Behavior 🤔

When table columns are rendered with items containing variable heights the heights should adjust, for example, if there is a cell A in column 1 with items Cars, Houses, Fans all broken down into a list, right now only Cars show up as the column height do not adjust accordingly.

**Comment by ighotouch** [comment]
This issue is in cellContent.js if the height of 42 is removed, this is resolved

**Comment by LeandroTorresSicilia** [comment]
@ighotouch  Sorry for the late response and thanks for the feedback
We already are discussing the possible solutions and use cases. Definitively removing the height in cellContent.js can be a good solution.

**Comment by TahimiLeonBravo** [comment]
let's change the `height: 42px` by `min-height: 42px`on the `cellContent.js` file

**Comment by ighotouch** [comment]
Setting a min hight should work.

**Comment by TahimiLeonBravo** [comment]
@ighotouch 
We are launching a new release of react-rainbow-components v1.13.0 🎉
This bug has been fixed, we are going to close this issue :)

**Comment by ighotouch** [comment]
Thanks @TahimiLeonBravo
