### ISSUE TITLE
fix: not contain hour24 prop in v1.12.0

### ISSUE THREAD

**Issue by nobv** [nexxtway/react-rainbow#1385]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

According to release note of [v1.12.0](https://github.com/nexxtway/react-rainbow/releases),
include new features of `hour24` prop.
But It seems that, that version didn't include `hour24`.

**Comment by LeandroTorresSicilia** [comment]
Thanks for the feedback.
It was added in v1.12.0 and works fine but it was not added to the typescript declaration file and if you want to use it with typescript then it will not let you.
This also is already fixed and will be released in the next version in a few days.

**Comment by nobv** [comment]
@LeandroTorresSicilia 
Thanks for the reply.
As you say, I wanted to use with typescript.
But ok, It's good news for me.
Thanks again for let me know that news.

**Comment by TahimiLeonBravo** [comment]
@nobv 
We are launching a new release of react-rainbow-components v1.13.0 🎉
This bug has been fixed, we are going to close this issue :)
