### ISSUE TITLE
test: add test to the Tree component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1423]
#### Requirements
- [x] Add unit tests
- [x] Add integration tests

###### child
- [ ] should render the PrimitiveCheckbox component when isChecked prop is true
- [ ] should render the PrimitiveCheckbox component when isChecked prop is false
- [ ] should render the PrimitiveCheckbox component when isChecked prop is "indeterminate"
- [ ] should render the TreeChildren component when children prop is not undefined

###### expandCollapseButton
- [ ] should return the Spinner component when isLoading prop is true
- [ ] should return the ButtonIcon component when hasChildren prop is true
- [ ] should set the right icon when isExpanded prop is true
- [ ] should set the right icon when isExpanded prop is false
- [ ] should fire onclick callback when ButtonIcon is clicked

###### tree
- [ ] should call onExpandCollapse with the right parameters when the button is clicked
- [ ] should render the correct number of children

###### getNode
- [ ] should return the correct node according to the parameters

###### tree-1
- [ ] should expand the node when it is collapse and its button icon is clicked
- [ ] should collapse the node when it is expand and its button icon is clicked
- [ ] should move focus to the next button icon when the first button icon is focused and press tab
- [ ] should expand the node when its button icon is focused and press enter
- [ ] should collapse the node when its button icon is focused and press enter
- [ ] should expand the node when its button icon is focused and press space
- [ ] should collapse the node when its button icon is focused and press space

**Comment by LeandroTorresSicilia** [comment]
Add these test cases:

###### tree
- [ ] should call onSelect with the right parameters when the button is clicked

###### getNode
here we need two test cases:
1. when return firstNode
2. when it is recursive
