### ISSUE TITLE
fix: TimePicker am/pm select when clicking on the selected element

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1475]
https://drive.google.com/drive/u/2/folders/1rZEIq4TxqbFkdyaCu8g-Sh7Zym1dHaBJ

#### Steps to reproduce
1. Go to TimePicker component https://react-rainbow.io/#!/TimePicker/3
2. Click on the TimePicker input
3. Click on the "PM" element

#### Current Behavior
When clicking on the selected element on the "AM-PM" it doesn't close.

#### Expected Behavior
When clicking any element on the "AM-PM" it should close them

**Comment by Anyrob** [comment]
Hi! I sent request access for the added document,
meanwhile, would you mind to giving me more context about it, please?

**Comment by TahimiLeonBravo** [comment]
Hi @Anyrob the bug happens when you try clicking on the selected value on the "am-pm", I am going to add the steps to reproduce the bug and the expected behavior

**Comment by Anyrob** [comment]
Thank you! I would like to work on this one :)

**Comment by TahimiLeonBravo** [comment]
> Thank you! I would like to work on this one :)

Great!! you are welcome!!

**Comment by Anyrob** [comment]
Hi @TahimiLeonBravo I think I solve it :) I'm gonna make my PR soon, but I noticed another bug, should I write it here?

**Comment by TahimiLeonBravo** [comment]
Great! @Anyrob I think you should make a PR with this fix and create a new issue for the new bug :)

**Comment by Anyrob** [comment]
Hey! @TahimiLeonBravo, I'm experiencing some problems with my internet connection but as soon as it is restored I'll make the PR! :)

**Comment by Anyrob** [comment]
Hi @TahimiLeonBravo just to notify you that my internet is better now :), and also, that I was trying to do the integration test before the PR, but I couldn't do it. I already identified where to write (Integration-specs-TimePicker-TimePricker-1.specs.js) and I was analyzing the ones that are there, however, I'm not being able to prove that it's working as expected. I already have a gif that shows the issue being solved, but I don't know if it's enough to show that it works. That's my only blocker to submit the PR, Do you have any recommendations for me?

**Comment by LeandroTorresSicilia** [comment]
Submit the PR without the test, we can create another issue to test it later
