### ISSUE TITLE
chore: styled-components version errors

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1485]
- update to the last styled-components version
- make sure the new version compatible with the old versions

**Comment by TahimiLeonBravo** [comment]
Some customer says they are getting this error:
`Unhandled Rejection (TypeError): Cannot read property 'palette' of undefined`

**Comment by blakmetall** [comment]
Revision update for this issue

Descriptions inside this file are in spanish, next time I upload a document here (in github) I will describe in english to keep standards... If english needed for this one, please confirm me to update the file.

[bug styled-components 5.1.0.pdf](https://github.com/nexxtway/react-rainbow/files/4651802/bug.styled-components.5.1.0.pdf)
