### ISSUE TITLE
feat: Support for MapBox in Map Component

### ISSUE THREAD

**Issue by ghost** [nexxtway/react-rainbow#1576]
I want to use [MapBox](https://www.mapbox.com/) in my app instead of using the default Google Maps implemented in GMaps Component. I think it would be better to have an option for choosing maps.

-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

**Comment by TahimiLeonBravo** [comment]
> I want to use [MapBox](https://www.mapbox.com/) in my app instead of using the default Google Maps implemented in GMaps Component. I think it would be better to have an option for choosing maps.
> 
> * [x]  I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

this was implemented in this library https://rainbow-modules.web.app/
