### ISSUE TITLE
docs: write documentation for "Option" component and remove the "PicklistOption" from the library UI

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1594]
#### Requirements:
- [ ] Improve documentation for "Option" component
        - improve component description (What is this component for?
)
- [ ] Remove the "PicklistOption" component from the library UI
(It needs to be able to continue to be used by users who already use it but we will not show this on the library UI)

@gtallesb I updated the task

**Comment by gtallesb** [comment]
got it
