### ISSUE TITLE
test: the InternalDropdown component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1611]
### Unit Tests Specs Proposal
Unit tests

- [x] should render svg and input elements when enableSearch is passed.
- [x] should not render svg and input elements when enableSearch is not passed.
- [x] should render loading icon when isLoading is passed.
- [x] should not render loading icon when isLoading is not passed.
- [x] should fire onChange with the right data when select one option and multiple is passed and there are no options selected.
- [x] should fire onChange with the right data when select one option and multiple is passed and have other options selected.
- [x] should fire onChange with the right data when deselecting one option and multiple is passed and have other options selected.

### Integration Tests Specs Proposal
- [x] should render only filtered options when type in search.
- [x] should render EmptyMessage component when no results found in the search.
- [x] should not render EmptyMessage component when displaying options.
- [x] should render Arrow component at top of the list of options when scrolling down the list.
- [x] should not render Arrow component at top of the list of options when scroll is at top of the list.
- [x] should render Arrow component at bottom of the list of options when scrolling top the list.
- [x] should not render Arrow component at bottom of the list of options when scroll is at bottom of the list.
- [x] should not render Arrow component when the list of options fits the container's height.
- [x] should Arrow component at top and bottom be visible both when first option and last options are not visible
- [x] should set active next option when press arrow down key
- [x] should select the option clicked
- [x] should select the option active when press enter key

**Comment by LeandroTorresSicilia** [comment]
other tests to add:
- [ ] should fire onChange with the right data when select one option and multiple is passed and there are no options selected
- [ ] should fire onChange with the right data when select one option and multiple is passed and have other options selected
- [ ] should fire onChange with the right data when deselecting one option and multiple is passed and have other options selected
- [ ] should render only filtered options when type in search
