### ISSUE TITLE
fix: performance issues in PhoneInput

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1650]
#### Description 
- When scrolls on the dropdown initially show slow
- Console is showing some warnings (https://www.chromestatus.com/feature/5745543795965952)
<img width="339" alt="Screen Shot 2020-06-07 at 9 23 20 AM" src="https://user-images.githubusercontent.com/32083556/85628955-a0c55e80-b636-11ea-8164-08c2a04518b2.png">

**Comment by PaulinaQuintero** [comment]
Hi! Could you give a detailed explanation of this issue?

**Comment by TahimiLeonBravo** [comment]
Hi! @PaulinaQuintero 
I just added some descriptions to this issue.

**Comment by marianayap** [comment]
@TahimiLeonBravo Hello! is this issue taken?

**Comment by TahimiLeonBravo** [comment]
Hello @marianayap you can take this issue

**Comment by marianayap** [comment]
@TahimiLeonBravo Hello! I click the link above but I don't have very clear where can I see the warnings and the reproduction link. Can I have more information?
