### ISSUE TITLE
fix: format the PhoneInput when copy and paste

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1651]
#### Requirements
- [ ] It should copy only the numbers if the value copied have other characters

**Comment by RicardoHE97** [comment]
Hi! I'm new to this project and I would like to contribute to it. Can I work on this issue?

**Comment by TahimiLeonBravo** [comment]
> Hi! I'm new to this project and I would like to contribute to it. Can I work on this issue?

You are welcome :) 
Go for it!
