### ISSUE TITLE
feat: add the props styles and className to Column Component.

### ISSUE THREAD

**Issue by yvmunayev** [nexxtway/react-rainbow#1771]
### Description
You cannot change the style of cells mainly padding, text-align and text-transform. You can partially solve this problem using the prop component. But there is use case like changing the style of the header that are not supported.

### Describe the solution you'd like
Add the props styles and className to Column Component.
These props will be applied to Cell Component

**Comment by TahimiLeonBravo** [comment]
I think that could be a bit confusing because it is not clear if that `className` and `style` are for the header or the cell.
I believe that for the use case of rendering a different header, we could pass on the header a `node` instead of a `string`

**Comment by yvmunayev** [comment]
@TahimiLeonBravo  was testing your idea, but I still have the limitation of changing the align of the header because the node is painted inside a Wrapper that is flex, to paint the header and the sort icon.

Another idea is to put a prop align to the Column Component with this prop I can configure the Wrapper flex of the header and the text-align of the cells

**Comment by reiniergs** [comment]
aligning of the header test will depend on the variant of the table, the default variant will always render to the `left`, the new variant you are implementing will always render `center`, we won't like that type of customization ... we don't want to allow changes on what we consider is `rainbow` UX

**Comment by yvmunayev** [comment]
In this way I cannot implement the interface as designed because the first column is aligned to the left and the other 3 to the center.

**Comment by yvmunayev** [comment]
![Screen Shot 2020-07-31 at 1 22 40 PM](https://user-images.githubusercontent.com/332409/89060377-f0cbcb00-d330-11ea-8032-ade4ff512832.png)

**Comment by TahimiLeonBravo** [comment]
@yvmunayev let's leave the headers centered in the new variant

**Comment by ldelia** [comment]
> @TahimiLeonBravo was testing your idea, but I still have the limitation of changing the align of the header because the node is painted inside a Wrapper that is flex, to paint the header and the sort icon.
> 
> Another idea is to put a prop align to the Column Component with this prop I can configure the Wrapper flex of the header and the text-align of the cells

I have a similar problem to what @yvmunayev has mentioned. The cell values are right-aligned in my use case since they are currency values. However, I would like to have the column header right-aligned as well. 

![image](https://user-images.githubusercontent.com/1646735/146042832-3757db2e-30d1-45a8-b696-56d55e750ee1.png)

How can we solve this problem?

**Comment by TahimiLeonBravo** [comment]
> > @TahimiLeonBravo was testing your idea, but I still have the limitation of changing the align of the header because the node is painted inside a Wrapper that is flex, to paint the header and the sort icon.
> > Another idea is to put a prop align to the Column Component with this prop I can configure the Wrapper flex of the header and the text-align of the cells
> 
> Hi @TahimiLeonBravo, I have a similar problem to what @yvmunayev has mentioned. The cell values are right-aligned in my use case since they are currency values. However, I would like to have the column header right-aligned as well.
> 
> ![image](https://user-images.githubusercontent.com/1646735/146042832-3757db2e-30d1-45a8-b696-56d55e750ee1.png)
> 
> How can we solve this problem?
> 
> Thanks in advance!

Hello @ldelia, thanks for using `react-rainbow-components`, currently it is not possible to right-align the header of a column, we will be working on a solution for that soon, I will notify you when it is available.
I have created a new issue for this feature this is the link https://github.com/nexxtway/react-rainbow/issues/2337, you can follow the progress there.

**Comment by TahimiLeonBravo** [comment]
Hello @ldelia the new version `1.29.0` with the feature to align the header of the table columns is now available

**Comment by ldelia** [comment]
@TahimiLeonBravo Thank you for letting me know! You all rock!
