### ISSUE TITLE
feat: add prop `icon` to the `FileSelector` component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1800]
### Specs
- [ ] Implement new prop
- [ ] Add test

### Requirements
- [ ] It should receive a node
- [ ] It should render the current icon when the `icon` prop is not passed
- [ ] Add a new InteractiveExample
https://zpl.io/brZAnND

### Usage
```
<FileSelector icon={<UploadImageIcon />} />
```

**Comment by bobbylemm** [comment]
Hello, I am new here and looking for a good first issue, this looks like a good one. If it has not been worked on, can I work on it?
