### ISSUE TITLE
test: for `ColorPicker` component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1804]

**Comment by yvmunayev** [comment]
### Integration Test

- [ ] should focus the right common component when an tap key is pressed
- [ ] should focus the right color in default colors component when an arrow key is pressed
- [ ] should change color when saturation component is focused an arrow key is pressed

**Comment by yvmunayev** [comment]
@LeandroTorresSicilia check the specs and tell me if you think you have to add any
