### ISSUE TITLE
feat: add `orientation` prop on the `RadioGroup` and `CheckboxGroup` components

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#1824]
### Specs
- [ ] implement functionality
- [ ] add tests
- [ ] add interactive example

### Requirements
- [ ] It should have an `orientation` pop to control the position of the options on the components
- [ ] It should receive de `vertical | horizontal` values
- [ ] The default value should be `vertical`

**Comment by luisFilipePT** [comment]
@TahimiLeonBravo opened a pr for this issue, hope you don't mind 😊 

I don't agree with `codeclimate` so I will leave the suggestions open.

![image](https://user-images.githubusercontent.com/9373787/93657726-c80cab80-fa2c-11ea-9a2a-0c7a565d1a26.png)

Anything to change or improve just let me know

Thanks 🙌

**Comment by TahimiLeonBravo** [comment]
> @TahimiLeonBravo opened a pr for this issue, hope you don't mind 😊
> 
> I don't agree with `codeclimate` so I will leave the suggestions open.
> 
> ![image](https://user-images.githubusercontent.com/9373787/93657726-c80cab80-fa2c-11ea-9a2a-0c7a565d1a26.png)
> 
> Anything to change or improve just let me know
> 
> Thanks 🙌

Hello @luisFilipePT Thanks for collaborating in react-rainbow
