### ISSUE TITLE
fix: can't pass ref as a props for Input component

### ISSUE THREAD

**Issue by goodbeysr** [nexxtway/react-rainbow#1839]
Hello, I have an issue adding additional props for the input, for example when trying to bind ref prop to the component

##Screenshots
![image](https://user-images.githubusercontent.com/22368199/93767527-1332e400-fc10-11ea-93a8-50a72610353d.png)

## To Reproduce 🕹

Just try to attach a ref prop to the Input component

## Context 🔦

I'm using react-rainbow in a type-safe system (typescript) with react-hook-form and apparently ref is not allowed on the Input props so I can't bind their hooks with your component.

## Suggestion

I think a quick fix would be to add an optional property to the BaseProps interface

interface BaseProps {
    className?: string;
    style?: CSSProperties;
    ref?: any;
}

Or a more sophisticated :

interface BaseProps <T> {
    className?: string;
    style?: CSSProperties;
    ref?: T;
}

**Comment by LeandroTorresSicilia** [comment]
Hi @goodbeysr, you are right we need to define the ref type in the typescript declaration file of the component.
I think we should use a more specific type like `MutableRefObject` which is what `React.useRef` returns.
I will make a PR request fixing this for the Input, we need to also make this for other components.
Thank you for the feedback and it is great that you are using react-rainbow.

**Comment by LeandroTorresSicilia** [comment]
what we will do is to add ref in base props as you showed in the description then all component will have the ref defined

**Comment by TahimiLeonBravo** [comment]
@goodbeysr the issue has already been fixed and will be available in the new version 1.18.0 of react-rainbow-components
