### ISSUE TITLE
fix: FileSelector giving error in the console

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#1963]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

 I am getting an error in my console but this component is working as expect

##Screenshots

The error from the console

![image](https://user-images.githubusercontent.com/32335849/97809502-8b5be300-1c6d-11eb-9c87-9935f25fd1f3.png)

## To Reproduce 🕹

```
const [Image, setImage] = useState<Blob | string>("")
const [UploadeImage, setUploadeImage] = useState<string>("")

 <FileSelector
                                className="rainbow-m-around_small"
                                label="Selecteur de fichier"
                                placeholder="Glisser & déposer ou cliquer pour parcourir"
                                bottomHelpText="Selectionez seulement un fichier"
                                onChange={value =>{setImage(value[0]);setUploadeImage(URL.createObjectURL(value[0]))}}
                            />
```

## Expected Behavior 🤔

I would expect to have no error shown in the console

## Current Behavior 😯

When uploading an image I get an error inside my console

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Comment by TahimiLeonBravo** [comment]
Hi @maximegheraille we are working on the fix, soon we will publish a new official version with the fixed
