### ISSUE TITLE
fix: Button behavior

### ISSUE THREAD

**Issue by macari-dev** [nexxtway/react-rainbow#1969]
The component MenuButton does not receive the label prop and it is clearly used on the examples on the docs (using TS)

-   [ x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

The component MenuButton does not receive the label prop and it is clearly used on the examples on the docs
##Screenshots

## To Reproduce 🕹

```js
const your => (code) => here;
```

## Context 🔦

What are you trying to accomplish? How has this issue affected you?
Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Possible Solution**

Just add the prop to the types

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by TahimiLeonBravo** [comment]
Hi @macari-dev we are working on the issue, soon we will publish a new official version with the arrangement
