### ISSUE TITLE
feat: add icon instead of sidebar when screen is smaller than giving pixels 

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#1982]
**Is your feature request related to a problem? Please describe.**

When I am using the sidebar and the screen becomes to small ( on Iphone for example) I lose like 25% of the screen with the sidebar. It would be nice to have a hamburger or chosen icon to open the sidenav.

## Context 🔦

I have noticed that the website [https://react-rainbow.io/#/Components](https://react-rainbow.io/#/Components) is using what I would want.

![image](https://user-images.githubusercontent.com/32335849/98409540-5a1b5280-2073-11eb-80ac-19f0c7bd8f64.png)

**Comment by maxxgreene** [comment]
I think the sidebar and the hamburger menu are two different components, they share similar behavior but that doesn't mean they should be implemented together. I think one way you can archive that is by hiding the sidebar using className with media query ... then show the hamburger menu in the desired position(maybe top bar)

an easy way to implement a hamburger menu could be using the <Drawer />

**Comment by maximegheraille** [comment]
@maxxgreene I know it is possible to get this done by using media query's and transitions but they could implement an option to hide the component via a given boolean. That way it would be simple to use a button component that changes the changes the state of the boolean.

**Comment by reiniergs** [comment]
hiding the component could be done easily by using RenderIf wrapper e.g.
```
<RenderIf isTrue={condition|state}>
    <SideBar ... >
</RenderIf>
```
In my opinion, adding a prop won't add too much benefit
