### ISSUE TITLE
feat: add autohide after given time to the notification component

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#1986]
## Context 🔦

It would be nice if we could give as option a number of ms after which the notification while be hidden automatically

**Comment by TahimiLeonBravo** [comment]
@hello @maximegheraille, thanks for the recommendation, we will discuss your proposal

**Comment by reiniergs** [comment]
@maximegheraille check this https://rainbow-modules.web.app/?path=/story/modules-app-components--app-notification

basically, there are a bunch of modules that are OSS as well build on top of react-rainbow-components. There is a solution for what you are looking for(timeout a notification)

`rainbow-modules` is maintained for the same team
