### ISSUE TITLE
feat: implement `Path` and `PathStep` component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#2004]
### Requirements
- implement component
- add tests
- document example

### Design
https://zpl.io/2jzGNR4
https://zpl.io/V0K3vjl

### Usage
```
 <Path 
          currentStepName (string) 
          onClick (func)
>
           
           <PathStep
                   hasError (bool)
                   label (string/node)
                   name (string)
           />
 </Path>
```

**Comment by TahimiLeonBravo** [comment]
@wildergd we should make some fixes to the component
[ ] Selected PathStep should have an icon
[ ] Steps should be buttons
[ ] Animation for visual feedback when clicking on the step
[ ] Animation when hover step is a "nice to have"
[ ] Step with error should not disable previous steps
[ ] Error should be independent of the step selected state

**Comment by wildergd** [comment]
> @wildergd we should make some fixes to the component
> [ ] Selected PathStep should have an icon
> [ ] Steps should be buttons
> [ ] Animation for visual feedback when clicking on the step
> [ ] Animation when hover step is a "nice to have"
> [ ] Step with error should not disable previous steps
> [ ] Error should be independent of the step selected state

ok... i will do changes ASAP
