### ISSUE TITLE
fix: console error on Picklist

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2009]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When opening the Picklist I am getting a console error, but this does not effect the working of the component but it is making the webpage slowing down. I am using React functional components

##Screenshots

![image](https://user-images.githubusercontent.com/32335849/99851278-3251e180-2b7f-11eb-8ba5-331d0faaa601.png)

```
const ListAll = () => {
    return (
        <>
                <MDBCol md="8" className="offset-2" >
                <Picklist
                            id="picklist-1"
                            value={{ name: "option 3", label: "Central Park" }}
                            label="Select Building"
                            hideLabel
                          >
                             <Option name="header" label="Your Buildings" variant="header" />
                             <Option name="option 1" label="Experimental Building" />
                             <Option name="option 2" label="Empire State" />
                             <Option name="option 3" label="Central Park" />
                          </Picklist>
                </MDBCol>
            </MDBRow>
        </>)
}

export default ListAll
```

## Expected Behavior 🤔

I expect the code to run without any errors in the console

**Comment by TahimiLeonBravo** [comment]
@maximegheraille this will be fixed very soon :)
