### ISSUE TITLE
fix: labelAlignment does not work on TimePicker

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2012]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When looking at the [properties and methods](https://react-rainbow.web.app/#/TimePicker) there is a labelAlignment but it does not exist on the TimePickerProps interface.

##Screenshots

![image](https://user-images.githubusercontent.com/32335849/99887159-32ff7c00-2c42-11eb-8c51-a2f5096bad02.png)
![image](https://user-images.githubusercontent.com/32335849/99887164-4579b580-2c42-11eb-9b5f-7a9924f14f0f.png)

**Comment by TahimiLeonBravo** [comment]
Hi @maximegheraille Which version are you using of react-rainbow-components? this was added in version v1.19.0
