### ISSUE TITLE
fix: labelAlignment does not work on Textarea

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2013]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When looking at the [properties and methods ](https://react-rainbow.web.app/#/Textarea)there is a labelAlignment but it does not exist on the TextAreaProps interface.

##Screenshots

![image](https://user-images.githubusercontent.com/32335849/99887203-9db0b780-2c42-11eb-9dff-25501a90dbb9.png)

![image](https://user-images.githubusercontent.com/32335849/99887210-c173fd80-2c42-11eb-9343-f52a6b5bb40d.png)

```

**Comment by TahimiLeonBravo** [comment]
Hi @maximegheraille Which version are you using of react-rainbow-components? this was added in version v1.19.0

**Comment by maximegheraille** [comment]
> Hi @maximegheraille Which version are you using of react-rainbow-components? this was added in version v1.19.0

Hi, just tested it out with the v1.19.0 and it does work
