### ISSUE TITLE
fix: availableDates on WeekDayPicker

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2040]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When setting a custom availableDates array I keep getting this error
![image](https://user-images.githubusercontent.com/32335849/101262323-0ec19600-373e-11eb-856b-42cb7146b2ba.png)

The only way to fix this for the moment is to change the type Weekdays in the index.d.ts of WeekDayPicker but that is always going to be overridden when a new update comes.

## To Reproduce 🕹

```
import React, { useState } from 'react';
import { WeekDayPicker } from 'react-rainbow-components';

function MultipleWeekDayPicker() {
    const [days, setDays] = useState(["lundi"]);

    const handleOnChange = weekDays => {
        setDays(weekDays);
    };

    return (
      <div className="rainbow-display-flex">
      
        <WeekDayPicker
            id="weekday-picker-5"
          	locale={'FR-be'}
            availableDates={['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche']}
            label="Select your working days"
            value={days}
            multiple
            onChange={handleOnChange}
        />  

        </div>
    );
};

    <div className="rainbow-align-content_center rainbow-m-around_xx-large">
        <MultipleWeekDayPicker  />
    </div>
```

**Comment by HellWolf93** [comment]
@maximegheraille WeekDayPicker component handles the week days internally always in English. When you provide a locale, it will use JavaScript `Intl` API to format the output, but the component always expects its props in English.

```
<WeekDayPicker
    id="weekday-picker-5"
    locale={'FR-be'}
    availableDates={['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']}
    value="monday"
    multiple
/>  
```

**Comment by maximegheraille** [comment]
indeed, I can get the weekday component to show it in french but I cannot use the french names for the onChange event
