### ISSUE TITLE
fix: Lookup 'our robots ...' showing to fast (before the search function is called)

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2077]
## Describe the bug

I am using the lookup component to fetch data from the server. the debounce is set to true so it waits for the user to finish typing.

Weirdly when debugging I found out that the popup with the 'our robots did not find ...' came up before the search function executed (I can see the popup when i'm typing in the lookup field for a brief moment). I set the loading state as the first line in the search function but the popup still appears before it.

I guess this is a bug when using a await fetch within the lookup component.

##Screenshots

This is the state of the page when the first line of the search function gets called.
![image](https://user-images.githubusercontent.com/32335849/103425768-f3b73a00-4bb4-11eb-9a6a-3a57c941692e.png)

this is when the first line get called via the debugging 

![image](https://user-images.githubusercontent.com/32335849/103425785-0e89ae80-4bb5-11eb-9050-7a701032a3ad.png)

## Expected Behavior 🤔

I would expect the popup to wait before being sure that the search function is called first, so that the loading state can be set. because now it is the popup that appears first and then the state is set and after that the popup disappeared.

**Comment by LeandroTorresSicilia** [comment]
@maximegheraille look at the second example (https://react-rainbow.io/#!/Lookup/3) where we simulate this flow, here what you need to do is pass null to the options prop as the initial value since an empty array indicate that the options are empty.
We need to improve the options prop documentation to explain this use case

**Comment by maximegheraille** [comment]
@LeandroTorresSicilia you are right,

setting initial state like this with undefined (not null) works

 ` const [items, setItems] = React.useState<null | { Id: number, label: string, photo: string, index: number }[]>(null);`
