### ISSUE TITLE
fix: Chart highest point not showing as a point

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2086]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When using the Chart component and giving it data, the highest number here 40 at Octobre is not show a point like the other ones. when hovering over it I can see that the value is correct (40).

##Screenshots

![image](https://user-images.githubusercontent.com/32335849/104062098-1e7b4100-51fa-11eb-9260-7629890a5fe7.png)

![image](https://user-images.githubusercontent.com/32335849/104062241-64380980-51fa-11eb-8223-0756360441d4.png)

**Comment by HellWolf93** [comment]
@maximegheraille i'm not able to reproduce this issue, could you provide a live example?

**Comment by maximegheraille** [comment]
@HellWolf93  after looking around with the latest version, it seems be gone.
