### ISSUE TITLE
feat: Allow className to change ButtonMenu text color

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2118]
Hi,

I opened this issue #2057 and the given solution was to use styled component
There should be a way to not use a styled component to fix this, I do not really want to use styled components just for this.

I saw that this code did not work when trying to set the ButtonMenu color via a className (tailwindcss classes) or style.

```
import React from 'react';
import { ButtonMenu, MenuItem } from 'react-rainbow-components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faBell } from '@fortawesome/free-solid-svg-icons';

    <div className="rainbow-m-bottom_xx-large rainbow-p-bottom_xx-large">
        <GlobalHeader
            className="rainbow-p-bottom_xx-large rainbow-m-bottom_xx-large"
            src="images/user/user3.jpg"
        >
            <ButtonMenu
                menuAlignment="right"
                menuSize="x-small"
                label={"test label"}
                className="text-white font-bold dark:text-black"
              	style={{color:'white'}}
              	icon={<FontAwesomeIcon icon={faBell} />}
           
            >    <MenuItem label="Menu Item One"/>
              </ButtonMenu>
        </GlobalHeader>
    </div>
```

**Comment by KaranSingh1301** [comment]
hey @maximegheraille  @TahimiLeonBravo  I am new to open source contribution but I would like work for this bug #2057.  May I work on this ?

**Comment by LeandroTorresSicilia** [comment]
Hi @KaranSingh1301, this issue was closed since it is not a bug, the users have the ability to pass a node then they can change these styles.

Thanks for being part of the rainbow community.
