### ISSUE TITLE
Why not switch to styled-components or similar?

### ISSUE THREAD

**Issue by subhendukundu** [nexxtway/react-rainbow#2143]
I see we have a mix of css and styled-components.

Is the plan to completely switch to styled-components or keep a mix?

PS: Love the UI concepts. Planning to use it for a project I am working on.

**Comment by LeandroTorresSicilia** [comment]
@subhendukundu all the components are already using styled-components, the other styles we have are at the Application component where we have a style tag with some global styles, but we get rid of all CSS. Inside the example folder is where you will find some CSS but these are for examples purpose, they are not distributed with the library.

Thanks for using react-rainbow
