### ISSUE TITLE
fix: Typescript: date range support missing for Calendar and DatePicker, 'showCheckbox' missing from MultiSelect

### ISSUE THREAD

**Issue by rswingler** [nexxtway/react-rainbow#2149]
I found some minor typescript definition issues with the Calendar, DatePicker, and MultiSelect components.

-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

Typescript: The 'value' prop on Calendar and DatePicker are both missing support for date arrays, and the "showCheckbox" prop is missing entirely from the MultiSelect TS definition. Looks like these were left out during implementation; a very quick fix.

## To Reproduce 🕹

1. Create a new TS react project
2. Add a Calendar and DatePicker to the project
3. Pass a date array `[new Date(), new Date()]` on the value prop for the Calendar and DatePicker (to specify a date range)
4. The IDE will flag the date array as not applicable, and running a yarn build will fail
5. Add a MultiSelect to the same TS project
6. Add the "showCheckbox" prop to the MultiSelect
7. The IDE will flag "showCheckbox" as not applicable

## Expected Behavior 🤔

Typescript: Calendar and DatePicker should support the type `Date[]` for the "value" prop. MultiSelect should support the "showCheckbox?: Boolean" type.

## Current Behavior 😯

Typescript: Calendar and DatePicker do not support date ranges, ie passing a date array to the "value" prop causes the build to fail. The MultiSelect component does not recognize the "showCheckbox" prop.

## Context 🔦

These are simple omissions from the TS definition files for these components. Date ranges on Calendar and DatePicker are effectively broken in typescript. The "showCheckbox" functionality for MultiSelect is unavailable due to this bug.

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: macOS Big Sur
-   Browser: Chrome, Safari, Firefox

**Actual Solution**

Calendar/index.d.ts line 6:
```js
value?: string | Date | Date[];
```

DatePicker/index.d.ts line 4:
```ts
type Value = string | Date | Date[];
```

MultiSelect/index.d.ts line 29 (new line):
```ts
showCheckbox?: Boolean;
```

I have a local branch with these fixes, but it looks like I can't create a pull request without going through these steps first? Thanks!

**Comment by LeandroTorresSicilia** [comment]
@rswingler Thanks for creating this issue, you are welcome to submit a PR

**Comment by rswingler** [comment]
@LeandroTorresSicilia Thanks. Could you add me as a collaborator so I can create a branch? Or do I need to fork the repo and then create a PR?

**Comment by LeandroTorresSicilia** [comment]
@rswingler you can fork it and create the PR

**Comment by rswingler** [comment]
@LeandroTorresSicilia You're very welcome!
