### ISSUE TITLE
fix: cannot change carouselCard height, margin top

### ISSUE THREAD

**Issue by maximegheraille** [nexxtway/react-rainbow#2169]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

When using the carouselCard component and setting a custom classname with height and margin top, but it does not work.

After inspecting a bit, it seems the components adds a inline style with a height of 340px

this is my carouselCard
```

  <CarouselCard
            className="h-36 w-64 mx-auto mt-16 md:m-28 xl:w-6/12 xl:h-60 xl:mt-32"
            style={{ maxWidth: '50rem' }}
            disableAutoScroll={true}
            disableAutoRefresh={true}
          >

```

this is when inspecting in chrome dev tools
![image](https://user-images.githubusercontent.com/32335849/108758236-27766680-754b-11eb-9445-2311e034f9ce.png)

The carouselCard should not add a height because i cannot override it

**Comment by HellWolf93** [comment]
Hi @maximegheraille. The CarouselCard component is meant to fill its parent height. If the parent element of the CarouselCard does not have a specified height then it defaults to 340px.

To specify a height for the CarouselCard please set a height to its container.
