### ISSUE TITLE
Input for currency?

### ISSUE THREAD

**Issue by xplatsolutions** [nexxtway/react-rainbow#2224]
Is there an input type set to currency/money out of the box that may be using locale like the datepicker?

An example would be when set to 'US' local the input would show an input value like $10.00.

**Comment by LeandroTorresSicilia** [comment]
@xplatsolutions we don't have this type of input, but it would be a great addition to the library

**Comment by LeandroTorresSicilia** [comment]
@xplatsolutions We added an InputCurrency component that will use a local prop.
Closed by #2468
