### ISSUE TITLE
feat: add extra property or header to the Column component

### ISSUE THREAD

**Issue by antb-developer** [nexxtway/react-rainbow#2250]
## Add extra property to Column, may be name "extra", so that we can pass more data

```
<Column header="user" field="User" extra="user" component={example}/>
<Column header="image" field="url" extra="image" component={example}/>
```

now in this case, we are using single component i.e "example", to render 2 columns, we can make conditions by using extra in component 

## OR

Simply pass existing fields like, header to component, this is the solution too

**Comment by LeandroTorresSicilia** [comment]
@antb-developer we could simply bypass all extra props by default, that would be great, for now what you can do is:
```
<Column header="user" field="User" component={(props) => <Example {...props} extra="user" />}/>
```

**Comment by antb-developer** [comment]
thanks
