### ISSUE TITLE
fix: RainbowThemeContainer is missing from NPM package (v1.25.0)

### ISSUE THREAD

**Issue by cezarcarvalhaes** [nexxtway/react-rainbow#2251]
-   [ x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

RainbowThemeContainer is not present in npm package build. Not present in `react-rainbow-components/components/`. I upgraded to `@latest` (v1.25.0 as of this writing), refreshed, and the component is not present.

##Screenshots

## To Reproduce 🕹

1. Upgrade to latest: `yarn upgrade react-rainbow-components@latest`
2. Attempt to import `RainbowThemeContainer` or manually search node_modules for it.

```js
const your => (code) => here;
```

## Expected Behavior 🤔

Expect RainbowThemeContainer to be present in `react-rainbow-components/components/RainbowThemeContainer`

## Current Behavior 😯

RainbowThemeContainer is not present

## Context 🔦

What are you trying to accomplish? How has this issue affected you?

I realize I can use the Application component to accomplish the same use case. However, this component is publicly documented as available, and I thought you should know that folks currently can't access it. 

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: Mac OSX 11.4

**Possible Solution**

Redeploy the npm build with latest changes.

**Additional context/Screenshots**
<img width="264" alt="Screen Shot 2021-06-22 at 10 51 09 AM" src="https://user-images.githubusercontent.com/32689385/122947091-e3a03c00-d347-11eb-9b37-4bb56a86a435.png">

**Comment by LeandroTorresSicilia** [comment]
@cezarcarvalhaes Yes, that is because we don't have published a new version yet. We will try to publish a new one with all the new fix and features as soon as posible.

**Comment by LeandroTorresSicilia** [comment]
@cezarcarvalhaes we just released the 1.26.0 version, here you can find the RainbowThemeContainer
Thanks for using react-rainbow
