### ISSUE TITLE
[Question] Is it possible to style the DateTime Picker Modal

### ISSUE THREAD

**Issue by dkaplan88** [nexxtway/react-rainbow#2252]
### Description
**Is your discussion related to a problem? Please describe.**
For the [DateTimePicker](https://react-rainbow.io/#/DateTimePicker) - it is very difficult to style the modal that pops up. I have tried using the `<Application>` Component but that made changes that affected my entire application. Is it possible to just apply the theme to the modal or to make specific style changes to the modal?

### Describe the solution you'd like
Adding a class name that is for the Modal would also solve my problem.

**Comment by LeandroTorresSicilia** [comment]
@dkaplan88 if you install the latest version (v1.26.0) there a new component `RainbowThemeContainer` that you can use to wrap only the DateTimePicker, then pass your custom theme to it and only the DateTimePicker will gets modified by the theme wrapping it

**Comment by dkaplan88** [comment]
> Great @LeandroTorresSicilia this solved my issue! Thanks for your help!
