### ISSUE TITLE
Help: DatePickerModal showing previous month on Firefox only

### ISSUE THREAD

**Issue by RmnRss** [nexxtway/react-rainbow#2253]
On firefox only, the PickerModal doesn't display the month corresponding to the input date.

### Description

When using the PickerModal with `value={new Date()}` on Firefox the displayed month is one month behind the given date (e.g. for an input of 24th of June 2021, the picker will display the month of May and today will be marked as May 24th 2021).

It works perfectly fine on Chrome & Safari.

### Describe the solution you'd like

I'd like the PickerModal to work on Firefox, but I'm running out of idea has to what I'm doing wrong.

### Environment

-   OS: macOs BigSur 11.4
-   Browser: Firefox
-   Version: 89.0.2 (64 bits)

### Context 🔦

<img width="471" alt="Screenshot 2021-06-24 at 15 56 48" src="https://user-images.githubusercontent.com/33030781/123276778-c618d100-d505-11eb-8751-7f0be8207182.png">
<img width="493" alt="Screenshot 2021-06-24 at 15 56 38" src="https://user-images.githubusercontent.com/33030781/123276782-c749fe00-d505-11eb-921e-faa0ff9683fe.png">

**Comment by HellWolf93** [comment]
Hi @RmnRss, thanks for reporting this issue. I'm not able to reproduce it, I would appreciate if you could share a code snippet, and also wich version of the library you are using.

**Comment by RmnRss** [comment]
Hi @HellWolf93, 

Sorry for the late reply, we're using version 1.25.0, I've tried using the 1.26.0 but got the same results.

Here is a snippet of our component :

```javascript
export const DateTimePickerField: React.FC<
  TextFieldProps & {
    minimumDate?: Date
    maximumDate?: Date
  }
> = ({ minimumDate, maximumDate, ...props }) => {
  const { isOpen, close, open } = useDisclosure()
  const [field, , helpers] = useField<Date>(props.name)
  const ref = useRef<HTMLInputElement | null>(null)
  const [locale] = useUserLanguage()
  const { formats } = useIntl()

  return (
    <>
      <TextField
        {...props}
        ref={ref}
        caretHidden
        isValueInvisible
        leftAdornment={
          <PseudoValueLeftAdornment>
            {moment(field.value).format(formats.date)}
          </PseudoValueLeftAdornment>
        }
        isPointerCursor
        onFocus={() => {
          if (!isOpen) {
            open()
            ref.current?.blur()
          }
        }}
      />
      <DatePickerModal
        locale={locale}
        title={props.label}
        id={`${props.name}-date-picker`}
        maxDate={maximumDate}
        minDate={minimumDate}
        isOpen={isOpen}
        value={field.value}
        variant="single"
        selectionType="single"
        onRequestClose={close}
        onChange={(d) => {
          helpers.setValue(d)
          close()
        }}
      />
    </>
  )
}
```

And then it's used like this and initialised with a new Date() : 

```javascript
        <DateTimePickerField
          name="date"
          label={formatFieldMessage({ model, field: 'date' }, { capitalize: true })}
          maximumDate={today}
        />
```

Environnement : 
```
    "react": "17.0.2",
    "formik": "2.2.8",
    "react-rainbow-components": "1.25.0",
```

**Comment by HellWolf93** [comment]
@RmnRss sorry for the inconveniences, but I'm still not able to reproduce your issue. I have set up a quick repo [here](https://github.com/HellWolf93/rainbow-datepicker), I would appreciate if you could clone and test it on your environment and tell me if it works for you.

Thank you for your time.

**Comment by RmnRss** [comment]
@HellWolf93 Thanks for setting up the repo. Thanks to it we were able to identify that the issue was on our side, probably due to polyfills triggering when they should not on Firefox.

I'll leave the issue open for now and come back with the full solution once we know more.

**Comment by HellWolf93** [comment]
My pleasure, hope you find the solution soon.

**Comment by RmnRss** [comment]
So it turns out the issue was indeed from polyfills triggering when they should not. It was detecting that [formatRange](https://caniuse.com/mdn-javascript_builtins_intl_datetimeformat_formatrange) was not supported on firefox, thus triggering the polyfills and creating the issue on the Intl.DateTimeFormat methods, and on Firefox only.

The polyfill is [not using timezones](https://formatjs.io/docs/polyfills/intl-datetimeformat/#default-timezone), but our Date were which was creating a shift between the two Dates and using the last day of the previous month as a reference rather than the first day of the month.

So we ended up removing the formatRange polyfill to fix the issue.
