### ISSUE TITLE
fix: Unable to increase, decrease default Hour field on modal open in TimePicker on newer React 17

### ISSUE THREAD

**Issue by besspiny** [nexxtway/react-rainbow#2276]
Hello.
You have to click hour field to be able to manipulate it by arrows. It works correctly on React 16 but not on recent 17.
My investigation found that it's caused by React sending initial click event (made on TimePicker input field which opens modal;) )
which fires privateHandleClick registered in OutsideClick class, finds that it's ouside of modal and incorrectlytakes it for regular outside click and sets inputFocusedIndex: -1 in handleClickOutside

Just add TimePicker component on Ract 17 and see for yourself

**Possible Solution**
I fixed it temporary by adding firstclick:true property in OutsideClick constructor and simply setting to false on first privateHandleClick call skipping handleClickOutside call

**Comment by LeandroTorresSicilia** [comment]
Hi @besspiny thanks for reporting the issue, we are working on a solution

**Comment by LeandroTorresSicilia** [comment]
@besspiny the issue is fixed in the new release 1.27.0
