### ISSUE TITLE
fix: warning message when using the Table component

### ISSUE THREAD

**Issue by ldelia** [nexxtway/react-rainbow#2398]
-   [X] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Warning message when using the Table component since v1.30.0

I'm receiving the following warning message:
_Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports._

## Screenshots

![image](https://user-images.githubusercontent.com/1646735/166828646-e1ac3d70-39ae-41e7-a799-db271f9a23bc.png)

## To Reproduce 🕹

```
        <Table data={[{ id: 1, name: 'react-rainbow' }]} keyField="id">
          <Column header={null} field="name" />
        </Table>
```

**Comment by LeandroTorresSicilia** [comment]
@ldelia The fix will be in the next release, we plan to launch a new version this week

Thanks for opening an issue.

**Comment by LeandroTorresSicilia** [comment]
@ldelia the new version (1.30.1) is published with the fix
