### ISSUE TITLE
fix: FileSelector placeholder types

### ISSUE THREAD

**Issue by Chiaparini** [nexxtway/react-rainbow#2403]
In the docs we have the definition of the types of the `placeholder` prop for the `FileSelector` as a `union` of string and a node (as seem in the figure 1), but in the code we actually only have string as a placeholder (as seem in the figure 2).

Figure 1
![image](https://user-images.githubusercontent.com/7076940/171023014-6bcd1e7c-d752-40f9-8300-d566e6a15ac9.png)

Figure 2
![image](https://user-images.githubusercontent.com/7076940/171024676-29c68cfa-d201-4580-9755-baf7e90c6058.png)

A simple solution would be adding the correct type for the prop.

**Comment by LeandroTorresSicilia** [comment]
@Chiaparini  The fix will be in the next release, we plan to launch a new version this week.

Thanks for opening the issue.

**Comment by LeandroTorresSicilia** [comment]
@Chiaparini the new version (1.30.1) is published with the fix

**Comment by Chiaparini** [comment]
@LeandroTorresSicilia Thank you!
