### ISSUE TITLE
Disabling custom date/s in the calendar / date picker.

### ISSUE THREAD

**Issue by Elnatanv** [nexxtway/react-rainbow#2423]
While developing a booking platform, using react rainbow. (date picker) I notice I cant disable date/s easily.
I know i can disable min and max dates out of the box, but I didn't find a way to disable custom dates.
I love react rainbow, its so clean, easy to use and by far better than the other solutions, therefore i would like to see it implemented in this library besides finding another.
- - - 

In my opinion, it should be passed as an array which can have two kinds of data
1. single date as a string.
2. object with from (key) and to (key) with the dates as value (e.g: {from: Date, to: Date})

This way it will be easy to add to "src/components/Calendar)/day.js" a function similar to : ```isDisabled```
Looping through the array the user passed. validate each item e.g: (if string is date || ( typeof item object && item.from/to is date) ).
then based on the if statement to call a function:
1. If string, we can use compareDate, There is already ```compareDates``` helper, that can be used for the single date string.
2. It will be easy to add a new helper to check if a date is between the two dates from the object. setting the dates to 0 hour, and adding ```getTime()``` to the dates will help to create a oneliner to check if the date is between the two dates.
```
let dayDate = date.setHours(0,0,0,0).getTime(); 
let fromDate = dateStart.setHours(0,0,0,0).getTime(); 
let toDate = dateEnd.setHours(0,0,0,0).getTime(); 

return fromDate < dayDate < toDate
```

Right now i have bookings in the DB, from date to date, coming from the date picker. it will be great to get this data from the server and pass it to the picker as close as possible as it is in the DB and have disabled dates.
Also it will be amazing to let the room's owner to be able to disable specific dates. 

As i said it will be amaizng to be able to pass an array (or two - one for range disable / one for single)
and it will disable the dates needed.

After long time of reviewing the api and docs. i almost gave up.
i was thinking about using different library, but i like this one so much i ended up giving up on disabling dates for now.
i went through the code in git hub and i noticed its an "easy" fix. i could fork it and add the feature (i would love to do it and create a pull request) . therefore im here. Please share you thoughts with me.

**Comment by Elnatanv** [comment]
Thank you very much for replying. this is great. i like the idea of passing strings/date object. 
it works for me. i can loop through the dates' ranges and create an array with all the dates (as string or date object).
I will follow the changes. 
if there is anyway i can help i would love to contribute. please let me know.

**Comment by LeandroTorresSicilia** [comment]
@Elnatanv we will start working on this today.
Thanks for using react rainbow and open this issue with a valid use case, which will help to improve the library.

**Comment by LeandroTorresSicilia** [comment]
@Elnatanv We just launch the 1.31.0 version where the new feature is available, let us know if this work for you.
