### ISSUE TITLE
feat: add borderRadius prop to Modal

### ISSUE THREAD

**Issue by LeandroTorresSicilia** [nexxtway/react-rainbow#2542]
@TahimiLeonBravo let's add border requirments

**Comment by TahimiLeonBravo** [comment]
**Design:**
https://www.figma.com/file/bMnIxYEbFqybEemecEYHLt/rainbow-modules?node-id=109%3A4305&t=Nne8gMhlnOeQ9Bib-1

BorderRadius variant sizes:
semi-rounded: `10px`
semi-square: `4px`
