### ISSUE TITLE
fix: synchronization of hours and AM/PM in TimePicker

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#699]
### Expected behavior
1. Open TimePicker
2. Select the AM value
3. With the ArrowUp keyboard change the value of the hour input until the 12th arrives.
4. When you change the value to 12 or higher the value of AM/PM should be changed to PM

**Comment by blakmetall** [comment]
when minutes reach 60 should I add a new hour automatically too?

should I apply this inversely too?
