### ISSUE TITLE
feat: add `hour24` to the TimePicker component

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#757]

**Comment by alonsosfera** [comment]
Hey! Can I work on this?

**Comment by LeandroTorresSicilia** [comment]
@alonsosfera  Yeah, you are welcome to contribute

**Comment by TahimiLeonBravo** [comment]
Hi @alonsosfera 
We released a new version 1.12.0 where the `hour24` prop is available.
Thanks for your contribution :)
