### ISSUE TITLE
feat: add one example  using `NextJS`

### ISSUE THREAD

**Issue by TahimiLeonBravo** [nexxtway/react-rainbow#939]
https://nextjs.org/

**Comment by Omar-Aziz** [comment]
Are there any examples of using react rainbow in next.js?

**Comment by TahimiLeonBravo** [comment]
> Are there any examples of using react rainbow in next.js?

We don't have any examples yet.
Currently, there is an annoying problem with CSS in SSR. We are migrating our components to styled-components, which will solve the problem.
Although there could be a configuration that solves it, but we don't have it yet. Also, it would require an extra configuration step and we don't want the users to go through this process. It should work out of the box.

**Comment by ninja4web** [comment]
> > Are there any examples of using react rainbow in next.js?
> 
> We don't have any examples yet.
> Currently, there is an annoying problem with CSS in SSR. We are migrating our components to styled-components, which will solve the problem.
> Although there could be a configuration that solves it, but we don't have it yet. Also, it would require an extra configuration step and we don't want the users to go through this process. It should work out of the box.

Hi Tahini, could you please provide us the configuration which solves this issue? We have a `React` app developed using `react-rainbow-components` and now we want to serve it using `next.js`. Thank you in advance!

**Comment by TahimiLeonBravo** [comment]
Hi @ninja4web this issue is currently on our roadmap, we have been working on an example using next here
https://github.com/nexxtway/rainbow-next-experience/pull/1
I think this can help you

**Comment by ninja4web** [comment]
Thank you @TahimiLeonBravo for your help. I am able to use `react-rainbow-components` in a `next.js` app now. As we are using `CSS modules`, I had to add `cssModules: true` also. The final `next.config.js` is like:

```
const withCSS = require("@zeit/next-css");
const withSass = require("@zeit/next-sass");
const withFonts = require("next-fonts");
const withTM = require("next-transpile-modules")(["react-rainbow-components"]);

module.exports = withTM(
  withFonts(
    withCSS(
      withSass({
        enableSvg: true,
        cssModules: true,
        webpack: (config, options) => {
          return config;
        },
      })
    )
  )
); 
```

**Comment by gabeszrozsa** [comment]
With next@9.5 the above mentioned config didn't work for me. Next has built-in CSS & Sass support. 

I managed make it work with slight modifications:

```
const withFonts = require('next-fonts');
const withTM = require('next-transpile-modules')(['react-rainbow-components']);

module.exports = withTM(
  withFonts({
    enableSvg: true,
    webpack(config, options) {
      return config;
    },
  })
);
```

**Comment by Nafiz-Ahmed** [comment]
Thanks @gabeszrozsa i need this config..

**Comment by Nafiz-Ahmed** [comment]
![222](https://user-images.githubusercontent.com/52189243/105016452-d9160980-5a6c-11eb-8539-bba9113dd16f.JPG)
is this problem showing for webpack??

**Comment by Nafiz-Ahmed** [comment]
I don't know what the hell is this..

**Comment by LeandroTorresSicilia** [comment]
@Nafiz-Ahmed we just fixed it, in the next version you can use it, although you can find more issues with SSR in other components and we will be fixing them when they raise up. I will let you know when the next version is ready.

**Comment by Nafiz-Ahmed** [comment]
@LeandroTorresSicilia Thanks and congrats to you and your team..
Waiting for the new version..

**Comment by LeandroTorresSicilia** [comment]
@Nafiz-Ahmed the version 1.24.0 is released

**Comment by Nafiz-Ahmed** [comment]
Let's hit it...

**Comment by LeandroTorresSicilia** [comment]
In the new version 1.24.1, we have moved the fonts to a CDN, now react-rainbow-components works out of the box with Next js, I have updated the next experience example project (https://github.com/nexxtway/rainbow-next-experience), note there can be issues with specific components.

We wait for your feedback.
