### ISSUE TITLE
Left-aligned form field labels

### ISSUE THREAD

**Issue by dgorshkov** [nexxtway/react-rainbow#951]
## Expected Behavior
Field labels are left-aligned by default

## Context
The current center-aligned labels cause severe eye strain due to excessive eye movement between field label and field value.
https://www.uxmatters.com/mt/archives/2006/07/label-placement-in-forms.php

**Comment by reiniergs** [comment]
making the label left-aligned by default is a visual breaking chance, considering label alignment customization via an attribute.
