### ISSUE TITLE
Column header does not get updated

### ISSUE THREAD

**Issue by ighotouch** [nexxtway/react-rainbow#967]
In the table->column component, passing in a dynamic header does not get updated on component re-render.

-   [x ] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

`          
const {counter} = this.state;
     <Column
                    header={counter}
                    field="name"
                  />`

## To Reproduce 🕹

1. Create a table component with one or two columns having header set from state;
2. Try updating the state value

## Expected Behavior 🤔

Header should be updated when state value changes

## Current Behavior 😯
Header is not updated

**Comment by TahimiLeonBravo** [comment]
@ighotouch Thanks, we have fixed the issue, it will be available in the next release
