### ISSUE TITLE
feat: implement datetime component.

### ISSUE THREAD

**Issue by jerlyn06** [nexxtway/react-rainbow#970]
Hello! 

Looking to adapt react-rainbow on an enterprise project, and it's almost perfect except for a datetime picker component, that would essentially merge the individual date picker and the time picker.   

Is this something that is already available but I seem to have missed or something in the works?

**Comment by reiniergs** [comment]
having two fields (data & time) do not work for your use case? although, it will be a good addition to the library :)

**Comment by TahimiLeonBravo** [comment]
Hi,
@jerlyn06 We have designed a proposal for the DateTimePicker component.
Something like this is what you are looking for?
![Components DateTimePicker modal](https://user-images.githubusercontent.com/32083556/65275303-ff2f4080-daea-11e9-9eae-21ddad703ba7.png)
![Components DateTimePicker modal in mobile](https://user-images.githubusercontent.com/32083556/65275519-78c72e80-daeb-11e9-91e2-54f12588dc2d.png)

**Comment by jerlyn06** [comment]
> having two fields (data & time) do not work for your use case? although, it will be a good addition to the library :)

Unfortunately not very well. Thanks for taking this into consideration!

**Comment by jerlyn06** [comment]
> Hi,
> @jerlyn06 We have designed a proposal for the DateTimePicker component.
> Something like this is you looking for?
> 
> ![Components DateTimePicker prop](https://user-images.githubusercontent.com/32083556/65275621-a9a76380-daeb-11e9-87d0-a76840902c21.png)
> 
> This is one of the next components to implement in our roadmap

This is EXACTLY what I'm looking for, thank you. I would offer to contribute but I'm still learning React.

**Comment by TahimiLeonBravo** [comment]
@jerlyn06 
Thank you for the suggestion
We should be ready a beta version for the component on the next week.
Anyway you are welcome to contribute 😉

**Comment by TahimiLeonBravo** [comment]
@wildergd 
Links to designs in Zeplin 
https://zpl.io/bzL4koA
https://zpl.io/aRXZrdp
https://zpl.io/2pP5yA8

**Comment by TahimiLeonBravo** [comment]
@wildergd when we add the integration test for the component we can close the issue
