### ISSUE TITLE
fix: fix VisualPickerOption styles after de-selection in multiple mode (border is not removed)

### ISSUE THREAD

**Issue by sheminusminus** [nexxtway/react-rainbow#985]
-   [x] I have searched the [issues](https://github.com/nexxtway/react-rainbow/issues) of this repository and believe that this is not a duplicate.

## Describe the bug

Create a `VisualPicker` with `multiple={true}`. Select and then de-select one of the `VisualPickerOption` elements. The corner checkmark goes away as expected, but the active selection border (blue border) stays on the de-selected option until focus is blurred.

## Screenshots

✅ Correct visual state BEFORE being selected:

<img width="523" alt="Screen Shot 2019-09-22 at 3 19 01 AM" src="https://user-images.githubusercontent.com/9907610/65384421-ce682a80-dce7-11e9-8e9a-f66be0d8b719.png">

✅ Correct visual state WHILE selected:

<img width="518" alt="Screen Shot 2019-09-22 at 3 04 46 AM" src="https://user-images.githubusercontent.com/9907610/65384302-6bc25f00-dce6-11e9-9bbd-38e2aff6ce46.png">

🚫 **Incorrect** visual state after de-selection:

<img width="521" alt="Screen Shot 2019-09-22 at 3 04 54 AM" src="https://user-images.githubusercontent.com/9907610/65384304-78df4e00-dce6-11e9-8b81-7cfa50695131.png">

## To Reproduce 🕹

1. Go to react-rainbow web app's [VisualPicker demo with multiple selection](https://react-rainbow.web.app/#!/VisualPicker/3)
2. Click on any un-selected option
3. See that the visual state is correct (has border and corner checkmark)
4. Click on the same option to de-select it
5. See that the checkmark goes away, but the border remains until the element loses focus

## Expected Behavior 🤔

After being de-selected, an option should return to the same visual state as before it was selected, which is no blue border and no corner checkmark.

## Current Behavior 😯

After being de-selected, an option does not return to the same visual state as before it was selected.

## Context 🔦

Trying to use the `VisualPicker` with multiple selections allowed.

## Your Environment 🌎

**Desktop (please complete the following information):**

-   OS: macOS 12.4
-   Browser: Chrome 77
-   Version: 1.4.0 in local development, but this also exists in whatever version the [react-rainbow web demos](https://react-rainbow.web.app/#!/VisualPicker/3) are running on.

**Comment by TahimiLeonBravo** [comment]
@sheminusminus Thanks for the feedback.
We are working on a solution with a better experience https://github.com/nexxtway/react-rainbow/pull/987
